<?php
   
return array(  
    'homepage' => 1,
    'about-webbank' => 2,
    'become-partner' => 3,
    'brand-partners' => 4,
    'business-associations' => 5,
    'business-partners' => 6,
    'commercial-insurance' => 7,
    'compliance' => 8,
    'contact-us' => 9,
    'deposit-products' => 10,
    'forms' => 11,
    'newsroom-detail' => 12,
    'newsroom-listing' => 13,
    'online-privacy' => 14,
    'our-people' => 15,
    'privacy' => 16,
    'rates-fees' => 17,
    'savings' => 18,
    'security' => 19,
    'speciality-finance' => 20,
    'term' => 21,
    'time-deposits' => 22,
    'uigea' => 23,
    'usa-patriot-act' => 24,
    'working-at-webbank' => 25,
);
  
